name: ReleaseZipCI

on:
  push:
    branches: [ master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload Chromium Extension as a build artifact
      uses: actions/upload-artifact@v2
      with: 
        name: chromium-extension
        path: ./extension/

    - uses: actions/checkout@master
    - name: Replace all instances of 'chrome' with 'browser'
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "chrome"
        replace: "browser"
        include: "./extension/"
    - uses: actions/checkout@v2
    - name: Upload Firefox Extension as a build artifact
      uses: actions/upload-artifact@v2
      with: 
        name: firefox-extension
        path: ./extension/
