name: ReleaseZipCI

on:
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload Chromium Extension as a build artifact
      uses: actions/upload-artifact@v2
      with: 
        name: chromium-extension
        path: ./extension/

    - run: rm ./extension/manifest.json
    - run: cp ./alternates/firefox-manifest.json ./extension/manifest.json
    - run: find ./extension -type f -exec sed -i 's/chrome/browser/g' {} \;

    - name: Upload Firefox Extension as a build artifact
      uses: actions/upload-artifact@v2
      with: 
        name: firefox-extension
        path: ./extension/
